In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
phi=pd.read_csv("train.csv")
phi

ID     CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
0      0  0.95577   0.0   8.14     0  0.538  6.047   88.8  4.4534    4  307.0   
1      1  0.02875  28.0  15.04     0  0.464  6.211   28.9  3.6659    4  270.0   
2      2  1.22358   0.0  19.58     0  0.605  6.943   97.4  1.8773    5  403.0   
3      3  5.66637   0.0  18.10     0  0.740  6.219  100.0  2.0048   24  666.0   
4      4  0.04544   0.0   3.24     0  0.460  6.144   32.2  5.8736    4  430.0   
..   ...      ...   ...    ...   ...    ...    ...    ...     ...  ...    ...   
395  395  0.03615  80.0   4.95     0  0.411  6.630   23.4  5.1167    4  245.0   
396  396  0.17505   0.0   5.96     0  0.499  5.966   30.2  3.8473    5  279.0   
397  397  6.65492   0.0  18.10     0  0.713  6.317   83.0  2.7344   24  666.0   
398  398  0.13117   0.0   8.56     0  0.520  6.127   85.2  2.1224    5  384.0   
399  399  0.06466  70.0   2.24     0  0.400  6.345   20.1  7.8278    5  358.0   

     PTRATIO       B  LSTAT  MEDV  
0       21.0  306.38  17.28  14.8  
1       18.2  396.33   6.21  25.0  
2       14.7  363.43   4.59  41.3  
3       20.2  395.69  16.59  18.4  
4       16.9  368.57   9.09  19.8  
..       ...     ...    ...   ...  
395     19.2  396.90   4.70  27.9  
396     19.2  393.43  10.13  24.7  
397     20.2  396.90  13.99  19.5  
398     20.9  387.69  14.09  20.4  
399     14.8  368.24   4.97  22.5  

[400 rows x 15 columns]

In [4]:
# Import phi from train data set with loadtxt
phi = np.loadtxt("train.csv", dtype='float', delimiter=',', skiprows=1,
                 usecols=tuple(range(1, 14)))  
phi

array([[9.55770e-01, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.06380e+02, 1.72800e+01],
       [2.87500e-02, 2.80000e+01, 1.50400e+01, ..., 1.82000e+01,
        3.96330e+02, 6.21000e+00],
       [1.22358e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        3.63430e+02, 4.59000e+00],
       ...,
       [6.65492e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.96900e+02, 1.39900e+01],
       [1.31170e-01, 0.00000e+00, 8.56000e+00, ..., 2.09000e+01,
        3.87690e+02, 1.40900e+01],
       [6.46600e-02, 7.00000e+01, 2.24000e+00, ..., 1.48000e+01,
        3.68240e+02, 4.97000e+00]])

In [32]:
# Import y(MEDV) from train data set with loadtxt function
y = np.loadtxt("train.csv", dtype='float', delimiter=',', skiprows=1,
               usecols=14, ndmin=2)
y

array([[14.8],
       [25. ],
       [41.3],
       [18.4],
       [19.8],
       [20.6],
       [15. ],
       [13.4],
       [23.1],
       [19.8],
       [50. ],
       [22. ],
       [21.7],
       [ 5. ],
       [26.7],
       [ 8.3],
       [16.1],
       [20.2],
       [28.5],
       [20.8],
       [29.4],
       [24.3],
       [18.1],
       [22.1],
       [24. ],
       [39.8],
       [18.4],
       [27.1],
       [23.9],
       [24.5],
       [21.2],
       [19.2],
       [20. ],
       [29.6],
       [19.1],
       [10.5],
       [28.1],
       [29. ],
       [20.9],
       [20.6],
       [30.5],
       [22.4],
       [33.8],
       [16.6],
       [28.4],
       [19.6],
       [28.2],
       [13.5],
       [17.8],
       [14.2],
       [ 8.4],
       [13.1],
       [15.3],
       [22.9],
       [20.6],
       [14.4],
       [24.4],
       [22.4],
       [29.1],
       [19.2],
       [21. ],
       [ 7.4],
       [16.3],
       [21.7],
       [16.6],
       [20.3],
       [18

In [8]:
# Import phi_test from test data set using loadtxt
phi_test = np.loadtxt("test.csv", dtype='float', delimiter=',',
                      skiprows=1, usecols=tuple(range(1, 14)))
phi_test


array([[1.06120e-01, 3.00000e+01, 4.93000e+00, ..., 1.66000e+01,
        3.94620e+02, 1.24000e+01],
       [3.41090e-01, 0.00000e+00, 7.38000e+00, ..., 1.96000e+01,
        3.96900e+02, 6.12000e+00],
       [1.22472e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        2.46500e+01, 1.56900e+01],
       ...,
       [5.36000e-02, 2.10000e+01, 5.64000e+00, ..., 1.68000e+01,
        3.96900e+02, 5.28000e+00],
       [1.04690e-01, 4.00000e+01, 6.41000e+00, ..., 1.76000e+01,
        3.89250e+02, 6.05000e+00],
       [4.55587e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.54700e+02, 7.12000e+00]])

In [11]:
# Min Max scaling for phi and phi_test (Feature Engineering)
for i in range(0, 13):
    col_max = max(phi[:, i])
    col_min = min(phi[:, i])
    phi[:, i] = (phi[:, i] - col_min) / (col_max - col_min)
    phi_test[:, i] = (phi_test[:, i] - col_min) / (col_max - col_min)

In [33]:
# Log scaling on y
y = np.log(y)

In [34]:
# Function to calculate change in error function
def delta_w(p, phi, w):
    if p == 2:
        deltaw = (2 * (np.dot(np.dot(np.transpose(phi), phi), w) -
                       np.dot(np.transpose(phi), y)) +
                  lambd * p * np.power(np.absolute(w), (p - 1)))
    if p < 2 and p > 1:
        deltaw = (2 * (np.dot(np.dot(np.transpose(phi), phi), w) -
                       np.dot(np.transpose(phi), y)) +
                  lambd * p * np.power(np.absolute(w), (p - 1)) * np.sign(w))
    return deltaw

In [35]:
# Dictionary containing filenames as keys and p as values
filenames = {'output.csv': 2.0,
             'output_p1.csv': 1.75,
             'output_p2.csv': 1.5,
             'output_p3.csv': 1.3
             }

In [36]:
# For each item in this dictionary
for (fname, p) in filenames.items():
    # Set initial w to zeros
    w = np.zeros((14, 1))

    # Hyperparameter lambda value
    lambd = 0.2

    # Maximum step size
    t = 0.00012

    # Calculate new value of w
    w_new = w - t * delta_w(p, phi, w)

    i = 0
    # Repeat steps until error between consecutive w is less than threshold
    while(np.linalg.norm(w_new-w) > 10 ** -10):
        w = w_new
        w_new = w - t * delta_w(p, phi, w)
        i = i + 1

    # Load values of id
    id_test = np.loadtxt("test.csv", dtype='int', delimiter=',',
                         skiprows=1, usecols=0, ndmin=2)

    # Calculate y for test data
    y_test = np.exp(np.dot(phi_test, w_new))

   
    # Save the ids and y
    np.savetxt(fname, np.concatenate((id_test, y_test), axis=1),
               delimiter=',', fmt=['%d', '%f'], header='ID,MEDV', comments='')
    